name: CI - QA Automation Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Instalar dependencias para TODOS los proyectos
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pytest-html selenium

      # 4. Instalar Google Chrome en el runner
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 5. Ejecutar pruebas en todo el repo y generar reporte HTML
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q --html=report.html --self-contained-html

      # 6. Subir reporte como artefacto
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html

      # 7. Subir screenshots como artefacto (si existen)
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: Proyecto2_Ecommerce_Selenium/screenshots
